### ISSUE TITLE
Trip Monitoring TODO list

### ISSUE THREAD

**Issue by landonreed** [ibi-group/otp-middleware#70]
Pending back end items for trip monitoring (note: UI work on hold until progress is made here):
- [x] save monitored trip flow (validate that itinerary exists before persisting monitored trip) - @landonreed => @binh-dam-ibigroup => #77 
- [x] prevent multiple, consecutive "itinerary not found" notifications from being sent to user - @binh-dam-ibigroup => See comments below.
- [x] (issue with decoding the OTP response, too many files open error) - @binh-dam-ibigroup => #74 
- [ ] http endpoint for monitoring trip (in addition to current sms/email) (consider navigation when designing) = ?
- [x] the check for if a trip is possible/exists during monitoring is very primitive right now... definitely needs some work (determine best approach possibly checking GTFS for trips, stops) - ?? => #357, #364
- [x] Pause trip monitoring if some threshold of "trip not found" is met, set status enum (TRIP_NO_LONGER_POSSIBLE, etc.) on monitored trip (that we can show in the UI) - ?? => #326 
- [x] change in monitored trip monitoring window settings - @evansiroky => #75
- [x] Recalculate for current day (plan trip at the appropriate time) - @evansiroky => #75

- ~The phone number validation flow looks a bit awkward as it requires extra /api/secure/user PUT operations in order to get the phone number validated. See https://github.com/ibi-group/otp-middleware/pull/33/files#r483187826. (current phone validation PR https://github.com/opentripplanner/otp-react-redux/pull/224 implements a workaround.)~ => Moved to #79.

**Comment by binh-dam-ibigroup** [comment]
I found the root cause for most of of the "Itinerary not found" notifications I was receiving. Basically, the stop id changed between the time I set the notification and when the checks occurred, causing a mismatch in the itinerary comparisons. The stop id changed because of a GTFS change that modified an agency id (agency ids are used in OTP's global stop ids). Recreating a monitored trip seems to have resolved the issue.

**Comment by binh-dam-ibigroup** [comment]
Another cause for an "Itinerary not found" notification is that the UI is saving real-time itineraries (which is incorrect) and trying to compare such itineraries with the updated itineraries from OTP that also include real-time updates. Comparing itineraries with real-time updates is unlikely to succeed IMO.
